### ISSUE TITLE
Compress message data

### ISSUE THREAD

**Issue by bakurits** [bakurits/mattermost-plugin-anonymous#49]
Now we are converting JSON stringified string to base64 here
https://github.com/bakurits/mattermost-plugin-anonymous/blob/3aafcbb6a8ead24b810e89abc91081374a60b6b7/webapp/src/hook/hook.js#L100

It's increasing message size about 4/3. Let's save JSON stringified message instead

**Comment by LashaBuxo** [comment]
I'd like to do this task
