### ISSUE TITLE
Cannot import back a private key

### ISSUE THREAD

**Issue by vixxtor** [bakurits/mattermost-plugin-anonymous#60]
If i print my private key with 
/anonymous keypair --export
I get a string like:
LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBekt3ckVEVzUwSjIyN1Q5dlRuaThDZWQyU3dOUklOVEUvNnVKUzlRZXU0QThrL1UxCmh1eUY4RmpvUXBZNDZlcDJFYmtSWGJUODBLdGpEK0JQNnFkdG9pNVI0clRRMUpOLzBuTlRUd3l3cm9FRTZIaEkKNE9KVVNEdHV4a2xDd29aRnpHbzZMUGZpQnhIL05NTkFIRVJrTSs0Q1ZXMFQrMEJKUUlERG9CTUpBTHFCUTNrNgpLWmVHWmpZRDJJWEtRVElJYUZuZDdZQWFVK0hUR0tXWW5rY1U1VE1hOFpyOXk1Y1RmWHdpN2VzREMzcGdiWTJHCi9jd1c5SkhtVHJpYkRwRnJRQ256SWRmYXhKaEV0WnFoTlAxNVB3R2lkVWl3VWVNVFNqT2dUT2prclQwV0xrcEgKSHVOYnlLdmFNQ1N5ZUVSYXdYVEJpdXpnLzRiS2owT1B4bUhKVlFJREFRQUJBb0lCQUNFWS9tWENxbWZIK1ZybwpWVEdWYUtNWllSSEVXWXc3bkJmVVA0R1pyZGFZYUROdEJkanB5c2NST1kzN0NQMGF3emtlZW1aeTdDYzZiK3lUClU1a1l0aXZ4M2FBUnFXdVc1cWE3cTQ4dStDdGdCZEVxRW03N2FyRzdtckJLREplMGF2a2hmSUxsR3hJVm9QV0IKVlk2OHFJK1ZQNTljNGt4Ukd3ZHBTemxKbXIwWklkNTBuMjRwQzBycFdKdUxJQ3VjMWtsV2pjanJEMGZsUU9ibApPSExxMEZicDJyWkNuK2FSRnhjVzEyRzF6Y21Mc0t6YVE5dHEzVmJLRDhrZUFGb0dsWGhPUDZjdDIzaVp1QmRFCjcxeEdxOENscWxVR3cyQTVIN214cHVKREtlQWNLL1o0UUp3WWRsMEFBMlpLTndvT0REMlpINGo3QjY4cTNMZE0KTTViYXlFRUNnWUVBNlQ0YWhTUnpDcnhia2Nldnc1WmhQN1ZLYWlPVUFpbElGRzVpanZvZlE1Wm4xc3JoM2FLdApZYlVGbkpYcy9ObC80MnphUUNqbzhaRGcyTU5ZUjVzV3VLSTlVNUVXRDZ4UDdOR1RTTGpONlI0OTlXSUVyUnhPClhJd3NFeWtBUkVsSWlHanhHRThaL2hrOWlSdFFQWHJndTFlajZWai92Y0M5cnN5NXRubURldTBDZ1lFQTRLUnkKT2o0dnRGVlhpTXg3ZjRZR3pGR01aOTVpdmMxQU5JcFRTVGNXVEhXSTVWekFPVFJXc1Q5UFNPMVhYUWFibWFOWApPaUlxM3A5R0I3ZjQ5QWxFNURYM1FMSkw4blVQTExtaW1oeEpwbmJTQURPbjZQUGRxaWxrUHdZQXgxaSsrYUpFCjluaitmem5oazc1RUVsVU1IOVVoUVVUWnY3aEdTUG1qb0I5eWN3a0NnWUVBaEg0T3Vvc1Yvb2M0elByTjBTRGYKWlQwcVpGaUpmeURNSFM4SE5ZakhzYkVDazNUMEVONlQ5dWpKbzBWWE5kcW5WeDFDYlNmUUMwanRNTFRtdE9aWQpaZEZqWE5FUjR4MVMyWWZEVHBBTUI5eHgvYTRNVWZtK1did1dYVnZ4RnRrNkpxTFdNYVRkY3dZTGVwTFZaZGNqClNjaGpCKzdTZDR2Qk5FWi9TRFNHaDVFQ2dZQU83WDZWdGpvdlRwaUJnNjBWUFUvSVZnYnhoQXFsdURUekNOb2QKL0dZajhJK0hSbEdUdTVHak42VEtJTk4wWUJNSTg1ekJSVEg2RnpWdEgrR1FQZWx4RE5FQVlKakJaTnY4U2QydgpSZi95NnVScmxRTXNiTUFuSlpiK3hTUmFHdUNkOEJXTEYyRTZEUnViV01KblFYV0x5L3Jvdm0yRjJ2WDR0WFlWCkZ1SGhHUUtCZ1FDcGt2ckZLOGtBcUozckNkeURWTDVkbEMwaGNlSnhtdHIyejY4REJRbWlQWmFsY3JvR09sajYKV3JoSjl4dDMvNjArdk5TWWRuZmxPeU9IUjFRQnM1VjRtVUYvcklaMm9XRDRLSDI2UmdGcmVsZm9LT1U0QzVILwpYWmg3WUxUMHlRUGNZV2JrQ1FPUVJvWDZCYzJqKytURWt5NmZOSnNDNUp1b3NSMlNPbWk2b0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==

then I try to import it in another session with:
/anonymous keypair --overwrite LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBekt3ckVEVzUwSjIyN1Q5dlRuaThDZWQyU3dOUklOVEUvNnVKUzlRZXU0QThrL1UxCmh1eUY4RmpvUXBZNDZlcDJFYmtSWGJUODBLdGpEK0JQNnFkdG9pNVI0clRRMUpOLzBuTlRUd3l3cm9FRTZIaEkKNE9KVVNEdHV4a2xDd29aRnpHbzZMUGZpQnhIL05NTkFIRVJrTSs0Q1ZXMFQrMEJKUUlERG9CTUpBTHFCUTNrNgpLWmVHWmpZRDJJWEtRVElJYUZuZDdZQWFVK0hUR0tXWW5rY1U1VE1hOFpyOXk1Y1RmWHdpN2VzREMzcGdiWTJHCi9jd1c5SkhtVHJpYkRwRnJRQ256SWRmYXhKaEV0WnFoTlAxNVB3R2lkVWl3VWVNVFNqT2dUT2prclQwV0xrcEgKSHVOYnlLdmFNQ1N5ZUVSYXdYVEJpdXpnLzRiS2owT1B4bUhKVlFJREFRQUJBb0lCQUNFWS9tWENxbWZIK1ZybwpWVEdWYUtNWllSSEVXWXc3bkJmVVA0R1pyZGFZYUROdEJkanB5c2NST1kzN0NQMGF3emtlZW1aeTdDYzZiK3lUClU1a1l0aXZ4M2FBUnFXdVc1cWE3cTQ4dStDdGdCZEVxRW03N2FyRzdtckJLREplMGF2a2hmSUxsR3hJVm9QV0IKVlk2OHFJK1ZQNTljNGt4Ukd3ZHBTemxKbXIwWklkNTBuMjRwQzBycFdKdUxJQ3VjMWtsV2pjanJEMGZsUU9ibApPSExxMEZicDJyWkNuK2FSRnhjVzEyRzF6Y21Mc0t6YVE5dHEzVmJLRDhrZUFGb0dsWGhPUDZjdDIzaVp1QmRFCjcxeEdxOENscWxVR3cyQTVIN214cHVKREtlQWNLL1o0UUp3WWRsMEFBMlpLTndvT0REMlpINGo3QjY4cTNMZE0KTTViYXlFRUNnWUVBNlQ0YWhTUnpDcnhia2Nldnc1WmhQN1ZLYWlPVUFpbElGRzVpanZvZlE1Wm4xc3JoM2FLdApZYlVGbkpYcy9ObC80MnphUUNqbzhaRGcyTU5ZUjVzV3VLSTlVNUVXRDZ4UDdOR1RTTGpONlI0OTlXSUVyUnhPClhJd3NFeWtBUkVsSWlHanhHRThaL2hrOWlSdFFQWHJndTFlajZWai92Y0M5cnN5NXRubURldTBDZ1lFQTRLUnkKT2o0dnRGVlhpTXg3ZjRZR3pGR01aOTVpdmMxQU5JcFRTVGNXVEhXSTVWekFPVFJXc1Q5UFNPMVhYUWFibWFOWApPaUlxM3A5R0I3ZjQ5QWxFNURYM1FMSkw4blVQTExtaW1oeEpwbmJTQURPbjZQUGRxaWxrUHdZQXgxaSsrYUpFCjluaitmem5oazc1RUVsVU1IOVVoUVVUWnY3aEdTUG1qb0I5eWN3a0NnWUVBaEg0T3Vvc1Yvb2M0elByTjBTRGYKWlQwcVpGaUpmeURNSFM4SE5ZakhzYkVDazNUMEVONlQ5dWpKbzBWWE5kcW5WeDFDYlNmUUMwanRNTFRtdE9aWQpaZEZqWE5FUjR4MVMyWWZEVHBBTUI5eHgvYTRNVWZtK1did1dYVnZ4RnRrNkpxTFdNYVRkY3dZTGVwTFZaZGNqClNjaGpCKzdTZDR2Qk5FWi9TRFNHaDVFQ2dZQU83WDZWdGpvdlRwaUJnNjBWUFUvSVZnYnhoQXFsdURUekNOb2QKL0dZajhJK0hSbEdUdTVHak42VEtJTk4wWUJNSTg1ekJSVEg2RnpWdEgrR1FQZWx4RE5FQVlKakJaTnY4U2QydgpSZi95NnVScmxRTXNiTUFuSlpiK3hTUmFHdUNkOEJXTEYyRTZEUnViV01KblFYV0x5L3Jvdm0yRjJ2WDR0WFlWCkZ1SGhHUUtCZ1FDcGt2ckZLOGtBcUozckNkeURWTDVkbEMwaGNlSnhtdHIyejY4REJRbWlQWmFsY3JvR09sajYKV3JoSjl4dDMvNjArdk5TWWRuZmxPeU9IUjFRQnM1VjRtVUYvcklaMm9XRDRLSDI2UmdGcmVsZm9LT1U0QzVILwpYWmg3WUxUMHlRUGNZV2JrQ1FPUVJvWDZCYzJqKytURWt5NmZOSnNDNUp1b3NSMlNPbWk2b0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==

it fails saying 'Invalid private key'.

**Comment by bakurits** [comment]
Thanks for reporting, @vixxtor. You can try the new version and we are here in case of any problem
